spring:
  application:
    name: user-service
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name}
      config:
        enabled: true