spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/acg-social-cfg?serverTimezone=UTC-5
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public