import type { Metadata } from "next";

import "./globals.css";
import DashboardHeader from "@/app/components/dashboard/dashboardHeader";
import React from "react";
import DashboardBackGround from "@/app/components/dashboard/dashboardBackGround";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <html lang="en">
        <body>
          <DashboardHeader/>
          <DashboardBackGround/>
          {children}
        </body>
    </html>

  );
}
